export const FINANCIAL_NOTIFICATION_EVENTS = [
  { code: "RECEIVABLE_INSTALLMENT_CANCELED", group: "CONTAS A RECEBER", name: "PARCELA CANCELADA" },
  { code: "RECEIVABLE_MOVEMENT_CANCELED", group: "CONTAS A RECEBER", name: "MOVIMENTO CANCELADO" },
  { code: "RECEIVABLE_INSTALLMENT_AMOUNT_CHANGED", group: "CONTAS A RECEBER", name: "VALOR DA PARCELA ALTERADO" },
  { code: "RECEIVABLE_INSTALLMENT_DUE_DATE_CHANGED", group: "CONTAS A RECEBER", name: "VENCIMENTO DA PARCELA ALTERADO" },
  { code: "RECEIVABLE_SETTLEMENT_REVERSED", group: "CONTAS A RECEBER", name: "RECEBIMENTO ESTORNADO" },
  { code: "PAYABLE_INSTALLMENT_CANCELED", group: "CONTAS A PAGAR", name: "PARCELA CANCELADA" },
  { code: "PAYABLE_MOVEMENT_CANCELED", group: "CONTAS A PAGAR", name: "MOVIMENTO CANCELADO" },
  { code: "PAYABLE_INSTALLMENT_AMOUNT_CHANGED", group: "CONTAS A PAGAR", name: "VALOR DA PARCELA ALTERADO" },
  { code: "PAYABLE_INSTALLMENT_DUE_DATE_CHANGED", group: "CONTAS A PAGAR", name: "VENCIMENTO DA PARCELA ALTERADO" },
  { code: "PAYABLE_SETTLEMENT_REVERSED", group: "CONTAS A PAGAR", name: "PAGAMENTO ESTORNADO" },
  { code: "CASH_MOVEMENT_CANCELED", group: "CAIXA", name: "MOVIMENTO DE CAIXA CANCELADO" },
] as const;

export type FinancialNotificationEventType =
  (typeof FINANCIAL_NOTIFICATION_EVENTS)[number]["code"];

export const FINANCIAL_NOTIFICATION_EVENT_CODES =
  FINANCIAL_NOTIFICATION_EVENTS.map((event) => event.code);

export function getFinancialNotificationEvent(code: string) {
  return FINANCIAL_NOTIFICATION_EVENTS.find((event) => event.code === code);
}
