'use client';

import { useEffect, useMemo, useState } from 'react';
import GridColumnFilterHeader from '@/app/components/grid-column-filter-header';
import GridExportModal from '@/app/components/grid-export-modal';
import GridStandardFooter, { type GridStatusFilterValue } from '@/app/components/grid-standard-footer';
import ScreenNameCopy from '@/app/components/screen-name-copy';
import { buildDefaultExportColumns, exportGridRows, type GridColumnDefinition, type GridExportFormat } from '@/app/lib/grid-export-utils';
import { useFinanceRuntimeContext } from '@/app/lib/runtime-context';
import { withFinanceBasePath } from '@/app/lib/public-path';
import { postMessageToTrustedParent } from '@/app/lib/trusted-messaging';

type SystemUser = { id: string; name: string; email: string; role: string; active: boolean; updatedAt: string };
type GridKey = 'name' | 'email' | 'role' | 'status';
type Sort = { key: GridKey | null; direction: 'ASC' | 'DESC' };
type Filters = Record<GridKey, string>;

const SCREEN_ID = 'PRINCIPAL_FINANCEIRO_MSINFOR_USUARIOS_SISTEMA';
const POPUP_SCREEN_ID = 'POPUP_FINANCEIRO_MSINFOR_USUARIOS_SISTEMA_CONFIGURACOES_USUARIO';
const cardClass = 'rounded-3xl border border-slate-200 bg-white shadow-sm';
const GRID_STORAGE_KEY = 'financeiro:msinfor:usuarios-sistema:grid-columns';
const GRID_COLUMNS: GridColumnDefinition<SystemUser, GridKey>[] = [
  { key: 'name', label: 'USUÁRIO', getValue: (row) => normalizedText(row.name) },
  { key: 'email', label: 'E-MAIL', getValue: (row) => row.email },
  { key: 'role', label: 'PERFIL', getValue: (row) => normalizedText(row.role) },
  { key: 'status', label: 'SITUAÇÃO', getValue: (row) => row.active ? 'ATIVO' : 'INATIVO' },
];
const EMPTY_FILTERS: Filters = { name: '', email: '', role: '', status: '' };

function normalizedText(value: unknown) { return String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleUpperCase('pt-BR'); }
function displayDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '-' : new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(date); }
function readVisibleColumns() { const defaults = GRID_COLUMNS.map((column) => column.key); if (typeof window === 'undefined') return defaults; try { const value = JSON.parse(window.localStorage.getItem(GRID_STORAGE_KEY) || 'null'); const selected = Array.isArray(value) ? defaults.filter((key) => value.includes(key)) : []; return selected.length ? selected : defaults; } catch { return defaults; } }

function ColumnSettingsModal({ isOpen, visible, onSave, onClose }: { isOpen: boolean; visible: GridKey[]; onSave: (value: GridKey[]) => void; onClose: () => void }) {
  const [draft, setDraft] = useState<GridKey[]>(visible);
  useEffect(() => { if (isOpen) setDraft(visible); }, [isOpen, visible]);
  if (!isOpen) return null;
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-900/60 p-4 backdrop-blur-sm"><section role="dialog" aria-modal="true" className="w-full max-w-xl overflow-hidden rounded-[28px] bg-white shadow-2xl"><header className="flex items-start justify-between gap-4 border-b border-slate-100 bg-slate-50 px-6 py-5"><div><div className="text-[11px] font-black uppercase tracking-[.28em] text-blue-600">CONFIGURAÇÃO DA TELA</div><h2 className="mt-1 text-2xl font-black text-slate-900">ALTERAR COLUNAS GRID</h2><p className="mt-2 text-sm font-medium text-slate-500">SELECIONE AS COLUNAS QUE DEVEM FICAR VISÍVEIS NESTE NAVEGADOR.</p></div><button type="button" onClick={onClose} className="rounded-full border border-slate-200 bg-white px-3 py-2 text-slate-500">✕</button></header><div className="space-y-3 p-6">{GRID_COLUMNS.map((column) => <label key={column.key} className="flex cursor-pointer items-center justify-between rounded-2xl border border-slate-200 bg-white px-4 py-4"><span className="text-sm font-black text-slate-700">{column.label}</span><input type="checkbox" checked={draft.includes(column.key)} onChange={() => setDraft((current) => current.includes(column.key) ? current.filter((key) => key !== column.key) : [...current, column.key])} className="h-5 w-5 accent-blue-600" /></label>)}</div><footer className="flex justify-between gap-3 border-t border-slate-100 px-6 py-5"><button type="button" onClick={() => setDraft(GRID_COLUMNS.map((column) => column.key))} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold text-slate-600">RESTAURAR PADRÃO</button><button type="button" onClick={() => { if (draft.length) { onSave(draft); onClose(); } }} className="rounded-xl bg-blue-600 px-5 py-2 text-sm font-bold text-white">SALVAR</button></footer></section></div>;
}

export default function FinanceSystemUsersPage() {
  const runtimeContext = useFinanceRuntimeContext();
  const [users, setUsers] = useState<SystemUser[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selectedUser, setSelectedUser] = useState<SystemUser | null>(null);
  const [statusFilter, setStatusFilter] = useState<GridStatusFilterValue>('ACTIVE'); const [columnFilters, setColumnFilters] = useState<Filters>(EMPTY_FILTERS); const [filterDrafts, setFilterDrafts] = useState<Filters>(EMPTY_FILTERS); const [activeFilter, setActiveFilter] = useState<GridKey | null>(null); const [sort, setSort] = useState<Sort>({ key: null, direction: 'ASC' });
  const [visibleKeys, setVisibleKeys] = useState<GridKey[]>(() => readVisibleColumns()); const [columnSettingsOpen, setColumnSettingsOpen] = useState(false); const [exportOpen, setExportOpen] = useState(false); const [exportFormat, setExportFormat] = useState<GridExportFormat>('excel'); const [exportColumns, setExportColumns] = useState(() => buildDefaultExportColumns(GRID_COLUMNS)); const [pageSize, setPageSize] = useState(10); const [page, setPage] = useState(1);
  const visibleColumns = useMemo(() => GRID_COLUMNS.filter((column) => (visibleKeys.length ? visibleKeys : GRID_COLUMNS.map((item) => item.key)).includes(column.key)), [visibleKeys]);

  useEffect(() => {
    if (!runtimeContext.embedded || window.parent === window) return;
    postMessageToTrustedParent({ type: 'MSINFOR_SCREEN_CONTEXT', screenId: SCREEN_ID });
  }, [runtimeContext.embedded]);

  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); if (runtimeContext.userRole !== 'ADMIN') { setLoading(false); return () => controller.abort(); } if (runtimeContext.sourceSystem !== 'ESCOLA') { setUsers([]); setError('A CONSULTA DE USUÁRIOS AINDA NÃO ESTÁ DISPONÍVEL PARA ESTE SISTEMA DE ORIGEM.'); setLoading(false); return () => controller.abort(); }
    void fetch('/api/v1/users', { credentials: 'include', headers: { Accept: 'application/json' }, signal: controller.signal }).then(async (response) => { const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.message || 'NÃO FOI POSSÍVEL CARREGAR OS USUÁRIOS DO SISTEMA.'); return Array.isArray(payload) ? payload : []; }).then((payload) => { if (!controller.signal.aborted) setUsers(payload.map((user) => ({ id: String(user?.id || ''), name: String(user?.name || ''), email: String(user?.email || ''), role: String(user?.role || ''), active: Boolean(user?.active), updatedAt: String(user?.updatedAt || '') })).filter((user) => user.id)); }).catch((requestError: unknown) => { if (!controller.signal.aborted) { setUsers([]); setError(requestError instanceof Error ? requestError.message.toUpperCase() : 'NÃO FOI POSSÍVEL CARREGAR OS USUÁRIOS DO SISTEMA.'); } }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [runtimeContext.sourceSystem, runtimeContext.userRole]);
  useEffect(() => { window.localStorage.setItem(GRID_STORAGE_KEY, JSON.stringify(visibleKeys)); }, [visibleKeys]);
  useEffect(() => { setPage(1); }, [search, statusFilter, columnFilters, sort, pageSize]);

  const displayedUsers = useMemo(() => users.filter((user) => { if (statusFilter === 'ACTIVE' && !user.active) return false; if (statusFilter === 'INACTIVE' && user.active) return false; if (search && !normalizedText(`${user.name} ${user.email} ${user.role}`).includes(normalizedText(search))) return false; return GRID_COLUMNS.every((column) => !columnFilters[column.key] || normalizedText(column.getValue(user)).includes(normalizedText(columnFilters[column.key]))); }).sort((a, b) => !sort.key ? 0 : normalizedText(GRID_COLUMNS.find((column) => column.key === sort.key)?.getValue(a)).localeCompare(normalizedText(GRID_COLUMNS.find((column) => column.key === sort.key)?.getValue(b)), 'pt-BR') * (sort.direction === 'ASC' ? 1 : -1)), [users, statusFilter, search, columnFilters, sort]);
  const totalPages = Math.max(1, Math.ceil(displayedUsers.length / pageSize)); const currentPage = Math.min(page, totalPages); const pagedUsers = displayedUsers.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const applyFilter = (key: GridKey) => { setColumnFilters((current) => ({ ...current, [key]: filterDrafts[key] })); setActiveFilter(null); }; const clearFilters = () => { setSearch(''); setColumnFilters(EMPTY_FILTERS); setFilterDrafts(EMPTY_FILTERS); setActiveFilter(null); setSort({ key: null, direction: 'ASC' }); };

  if (runtimeContext.userRole !== 'ADMIN') return <section className={`${cardClass} p-8 text-center`}><div className="text-[11px] font-black uppercase tracking-[.24em] text-amber-600">ACESSO RESTRITO</div><h1 className="mt-2 text-2xl font-black text-slate-900">USUÁRIOS DO SISTEMA</h1><p className="mt-2 text-sm font-semibold text-slate-600">ESTA ÁREA ESTÁ DISPONÍVEL SOMENTE PARA USUÁRIOS COM PERFIL ADMIN.</p></section>;
  return <div className="space-y-5"><section className={`${cardClass} overflow-hidden`}><div className="p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><label className="relative block w-full max-w-md"><span className="sr-only">PESQUISAR USUÁRIO</span><input value={search} onChange={(event) => setSearch(event.target.value.toUpperCase())} placeholder="PESQUISAR POR NOME, E-MAIL OU PERFIL..." className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 pr-10 text-xs font-bold text-slate-700 outline-none focus:border-blue-500" /><span className="pointer-events-none absolute right-3 top-2.5 text-lg text-slate-400">⌕</span></label><button type="button" onClick={clearFilters} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-[10px] font-black text-slate-600">LIMPAR FILTROS</button></div>
      <div className="overflow-x-auto rounded-xl border border-slate-200"><div className="min-w-[820px]"><div className="grid border-b border-slate-200 bg-slate-100 px-4 py-3 text-[10px] font-black tracking-wide text-slate-600" style={{ gridTemplateColumns: `repeat(${Math.max(visibleColumns.length, 1)}, minmax(150px, 1fr)) 145px` }}>{visibleColumns.map((column) => <GridColumnFilterHeader key={column.key} label={column.label} isOpen={activeFilter === column.key} isActive={Boolean(columnFilters[column.key])} filterValue={filterDrafts[column.key]} align={column.key === 'status' ? 'right' : 'left'} sortDirection={sort.key === column.key ? sort.direction : null} onToggle={() => setActiveFilter((current) => current === column.key ? null : column.key)} onSort={(direction) => { setSort({ key: column.key, direction }); setActiveFilter(null); }} onFilterValueChange={(value) => setFilterDrafts((current) => ({ ...current, [column.key]: value.toUpperCase() }))} onApply={() => applyFilter(column.key)} onClear={() => { setFilterDrafts((current) => ({ ...current, [column.key]: '' })); setColumnFilters((current) => ({ ...current, [column.key]: '' })); setActiveFilter(null); }} />)}<span className="text-right">AÇÃO</span></div>
      {loading ? <div className="px-4 py-10 text-center text-xs font-black text-slate-500">CARREGANDO USUÁRIOS...</div> : null}{!loading && error ? <div className="px-4 py-10 text-center text-xs font-black text-red-600">{error}</div> : null}{!loading && !error && pagedUsers.map((user, index) => <div key={user.id} className={`grid items-center border-b border-slate-100 px-4 py-3 text-xs last:border-b-0 ${index % 2 ? 'bg-slate-50/80' : 'bg-white'}`} style={{ gridTemplateColumns: `repeat(${Math.max(visibleColumns.length, 1)}, minmax(150px, 1fr)) 145px` }}>{visibleColumns.map((column) => <div key={column.key} className="min-w-0 pr-3">{column.key === 'name' ? <><div className="truncate font-black text-slate-800">{column.getValue(user)}</div><div className="mt-1 text-[10px] font-semibold text-slate-400">ATUALIZADO EM {displayDate(user.updatedAt)}</div></> : column.key === 'status' ? <span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-black ${user.active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600'}`}>{column.getValue(user)}</span> : <span className="truncate font-semibold text-slate-600">{column.getValue(user)}</span>}</div>)}<div className="text-right"><button type="button" onClick={() => setSelectedUser(user)} className="rounded-lg bg-[#153a6a] px-3 py-2 text-[10px] font-black text-white">CONFIGURAÇÕES</button></div></div>)}{!loading && !error && !pagedUsers.length ? <div className="px-4 py-10 text-center text-xs font-black text-slate-500">NENHUM USUÁRIO LOCALIZADO.</div> : null}</div></div></div>
    <GridStandardFooter statusFilter={statusFilter} totalRecords={displayedUsers.length} pageSize={pageSize} currentPage={currentPage} totalPages={totalPages} onColumnSettings={() => setColumnSettingsOpen(true)} onExport={() => setExportOpen(true)} onStatusFilterChange={setStatusFilter} onPageSizeChange={setPageSize} onPageChange={setPage} recordSummaryLabel="TOTAL REGISTROS" /></section>
    <ColumnSettingsModal isOpen={columnSettingsOpen} visible={visibleKeys} onSave={setVisibleKeys} onClose={() => setColumnSettingsOpen(false)} />
    <GridExportModal isOpen={exportOpen} title="EXPORTAR USUÁRIOS DO SISTEMA" description={`A EXPORTAÇÃO RESPEITA OS FILTROS E INCLUI ${displayedUsers.length} REGISTRO(S).`} format={exportFormat} onFormatChange={setExportFormat} columns={GRID_COLUMNS.map(({ key, label }) => ({ key, label }))} selectedColumns={exportColumns} storageKey="financeiro:msinfor:usuarios-sistema:export" brandingName={runtimeContext.companyName || 'FINANCEIRO'} brandingLogoUrl={runtimeContext.logoUrl} screenId={SCREEN_ID} blueHeader onClose={() => setExportOpen(false)} onExport={async (config) => { await exportGridRows({ rows: displayedUsers, columns: config.orderedColumns.map((key) => GRID_COLUMNS.find((column) => column.key === key)).filter((column): column is GridColumnDefinition<SystemUser, GridKey> => Boolean(column)), selectedColumns: config.selectedColumns, format: exportFormat, pdfOptions: config.pdfOptions, fileBaseName: 'usuarios-do-sistema', branding: { title: 'USUÁRIOS DO SISTEMA', subtitle: 'EXPORTAÇÃO COM OS FILTROS ATUALMENTE APLICADOS.', schoolName: runtimeContext.companyName || 'FINANCEIRO', logoUrl: runtimeContext.logoUrl } }); setExportColumns(config.selectedColumns); setExportOpen(false); }} />
    {selectedUser ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" onMouseDown={() => setSelectedUser(null)}><section role="dialog" aria-modal="true" aria-label="CONFIGURAÇÕES DO USUÁRIO" className="w-full max-w-2xl overflow-hidden rounded-2xl bg-white shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><header className="flex items-center gap-4 border-b border-slate-200 bg-[#153a6a] px-5 py-4 text-white"><div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-white p-1"><img src={runtimeContext.logoUrl || withFinanceBasePath('/logo-msinfor.jpg')} alt="LOGOTIPO DA ESCOLA" className="h-full w-full object-contain" /></div><div className="min-w-0 flex-1"><div className="text-[10px] font-black tracking-[.2em] text-blue-100">CONFIGURAÇÕES POR USUÁRIO</div><h2 className="truncate text-lg font-black">{normalizedText(selectedUser.name)}</h2></div><button type="button" onClick={() => setSelectedUser(null)} aria-label="FECHAR" className="rounded-lg px-2 py-1 text-2xl leading-none">×</button></header><div className="space-y-5 p-6"><div className="grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2"><div><div className="text-[10px] font-black text-slate-400">E-MAIL</div><div className="mt-1 text-xs font-bold text-slate-700">{selectedUser.email}</div></div><div><div className="text-[10px] font-black text-slate-400">PERFIL NA ORIGEM</div><div className="mt-1 text-xs font-black text-slate-700">{normalizedText(selectedUser.role)}</div></div></div><div className="rounded-xl border border-dashed border-slate-300 px-5 py-8 text-center"><div className="text-sm font-black text-slate-700">SEM CONFIGURAÇÕES OPERACIONAIS CADASTRADAS.</div><p className="mx-auto mt-2 max-w-lg text-xs font-semibold leading-5 text-slate-500">ESTE POPUP É O PONTO ÚNICO PARA AS PRÓXIMAS PERMISSÕES INDIVIDUAIS DO FINANCEIRO, COMO CANCELAMENTO DE ITEM OU VENDA.</p></div></div><footer className="flex items-center justify-between gap-3 border-t border-slate-200 px-5 py-3"><span className="text-[10px] font-black tracking-wide text-slate-400">CONSULTA INDIVIDUAL · SEM ALTERAÇÕES</span><ScreenNameCopy screenId={POPUP_SCREEN_ID} compact originText="Sistema Financeiro - configurações individuais de usuário." auditText="Popup individual para concentrar futuras permissões operacionais por usuário." /></footer></section></div> : null}
  </div>;
}
