CREATE TABLE "nfce_profiles" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyId" TEXT NOT NULL,
    "branchCode" INTEGER NOT NULL DEFAULT 1,
    "certificateId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "environment" TEXT NOT NULL DEFAULT 'HOMOLOGATION',
    "autoIssueOnSale" BOOLEAN NOT NULL DEFAULT false,
    "series" INTEGER NOT NULL DEFAULT 1,
    "nextNumber" INTEGER NOT NULL DEFAULT 1,
    "stateCode" TEXT NOT NULL,
    "cityCode" TEXT NOT NULL,
    "stateRegistration" TEXT NOT NULL,
    "legalName" TEXT NOT NULL,
    "tradeName" TEXT,
    "taxRegimeCode" TEXT NOT NULL,
    "street" TEXT NOT NULL,
    "number" TEXT NOT NULL,
    "complement" TEXT,
    "neighborhood" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "postalCode" TEXT NOT NULL,
    "phone" TEXT,
    "defaultCfopCode" TEXT NOT NULL DEFAULT '5102',
    "defaultOriginCode" TEXT NOT NULL DEFAULT '0',
    "defaultIcmsCst" TEXT NOT NULL DEFAULT '00',
    "defaultIcmsRate" REAL NOT NULL DEFAULT 0,
    "defaultPisCst" TEXT NOT NULL DEFAULT '08',
    "defaultCofinsCst" TEXT NOT NULL DEFAULT '08',
    "ibsCbsCst" TEXT NOT NULL DEFAULT '000',
    "ibsCbsClassCode" TEXT NOT NULL DEFAULT '000001',
    "ibsStateRate" REAL NOT NULL DEFAULT 0.1,
    "ibsMunicipalRate" REAL NOT NULL DEFAULT 0,
    "cbsRate" REAL NOT NULL DEFAULT 0.9,
    "additionalInformation" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdBy" TEXT,
    "updatedAt" DATETIME NOT NULL,
    "updatedBy" TEXT,
    "canceledAt" DATETIME,
    "canceledBy" TEXT,
    CONSTRAINT "nfce_profiles_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "nfce_profiles_certificateId_fkey" FOREIGN KEY ("certificateId") REFERENCES "fiscal_certificates" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE "fiscal_documents" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyId" TEXT NOT NULL,
    "branchCode" INTEGER NOT NULL DEFAULT 1,
    "saleId" TEXT NOT NULL,
    "profileId" TEXT NOT NULL,
    "certificateId" TEXT NOT NULL,
    "model" TEXT NOT NULL DEFAULT '65',
    "environment" TEXT NOT NULL,
    "series" INTEGER NOT NULL,
    "number" INTEGER NOT NULL,
    "randomCode" TEXT,
    "accessKey" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "statusCode" TEXT,
    "statusMessage" TEXT,
    "protocol" TEXT,
    "receivedAt" DATETIME,
    "issuedAt" DATETIME NOT NULL,
    "qrCodeUrl" TEXT,
    "signedXml" TEXT,
    "responseXml" TEXT,
    "processedXml" TEXT,
    "attemptCount" INTEGER NOT NULL DEFAULT 0,
    "lastAttemptAt" DATETIME,
    "lastError" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdBy" TEXT,
    "updatedAt" DATETIME NOT NULL,
    "updatedBy" TEXT,
    "canceledAt" DATETIME,
    "canceledBy" TEXT,
    CONSTRAINT "fiscal_documents_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fiscal_documents_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "sales" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fiscal_documents_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "nfce_profiles" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fiscal_documents_certificateId_fkey" FOREIGN KEY ("certificateId") REFERENCES "fiscal_certificates" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE "fiscal_document_attempts" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyId" TEXT NOT NULL,
    "fiscalDocumentId" TEXT NOT NULL,
    "attemptNumber" INTEGER NOT NULL,
    "status" TEXT NOT NULL,
    "statusCode" TEXT,
    "statusMessage" TEXT,
    "signedXml" TEXT,
    "responseXml" TEXT,
    "processedXml" TEXT,
    "errorMessage" TEXT,
    "attemptedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdBy" TEXT,
    "updatedAt" DATETIME NOT NULL,
    "updatedBy" TEXT,
    "canceledAt" DATETIME,
    "canceledBy" TEXT,
    CONSTRAINT "fiscal_document_attempts_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fiscal_document_attempts_fiscalDocumentId_fkey" FOREIGN KEY ("fiscalDocumentId") REFERENCES "fiscal_documents" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "nfce_profiles_companyId_branchCode_environment_key" ON "nfce_profiles"("companyId", "branchCode", "environment");
CREATE INDEX "nfce_profiles_companyId_branchCode_status_autoIssueOnSale_idx" ON "nfce_profiles"("companyId", "branchCode", "status", "autoIssueOnSale");
CREATE UNIQUE INDEX "fiscal_documents_saleId_key" ON "fiscal_documents"("saleId");
CREATE UNIQUE INDEX "fiscal_documents_accessKey_key" ON "fiscal_documents"("accessKey");
CREATE UNIQUE INDEX "fiscal_documents_companyId_branchCode_model_series_number_key" ON "fiscal_documents"("companyId", "branchCode", "model", "series", "number");
CREATE INDEX "fiscal_documents_companyId_branchCode_status_issuedAt_idx" ON "fiscal_documents"("companyId", "branchCode", "status", "issuedAt");
CREATE UNIQUE INDEX "fiscal_document_attempts_fiscalDocumentId_attemptNumber_key" ON "fiscal_document_attempts"("fiscalDocumentId", "attemptNumber");
CREATE INDEX "fiscal_document_attempts_companyId_attemptedAt_idx" ON "fiscal_document_attempts"("companyId", "attemptedAt");
